ALTER SESSION SET CURRENT_SCHEMA = estoque_teste;

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE services (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(150) NOT NULL,
    description VARCHAR2(500),
    status VARCHAR2(30) DEFAULT 'pending',
    user_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_services_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

INSERT INTO users (name, email, password)
VALUES ('Usuário Teste', 'teste@email.com', '123456');

INSERT INTO services (title, description, status, user_id)
VALUES ('Serviço de teste', 'Solicitação criada no banco de desenvolvimento', 'pending', 1);

COMMIT;






#-------------------------------------------
# Tabela de produtos para teste de estoque
#-------------------------------------------

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(50) NOT NULL,
    name VARCHAR2(150) NOT NULL,
    stock NUMBER DEFAULT 0
);

INSERT INTO products (code, name, stock)
VALUES ('1205000545865', 'Dipirona 500g', 200);

INSERT INTO products (code, name, stock)
VALUES ('1205000545866', 'Paracetamol 750mg', 150);

INSERT INTO products (code, name, stock)
VALUES ('1205000545867', 'Amoxicilina 500mg', 80);

COMMIT;