DROP TABLE IF EXISTS PRODUTO;

DROP TABLE IF EXISTS EST_PRO;

CREATE TABLE PRODUTO (

    CD_PRODUTO INTEGER PRIMARY KEY,

    DS_PRODUTO TEXT NOT NULL,

    QT_ESTOQUE_ATUAL INTEGER,

    SN_MEDICAMENTO TEXT,

    TP_STATUS_UNIFICADO TEXT
);

CREATE TABLE EST_PRO (

    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    CD_PRODUTO INTEGER,

    CD_ESTOQUE INTEGER,

    CD_LOCALIZACAO TEXT,

    QT_ESTOQUE_ATUAL INTEGER,

    DS_LOCALIZACAO_PRATELEIRA TEXT,

    DT_ULTIMA_MOVIMENTACAO TEXT,

    FOREIGN KEY (CD_PRODUTO)
    REFERENCES PRODUTO(CD_PRODUTO)
);